import 'customDesign.dart';
import 'favComponent.dart';

class list {
  static List lsito = [
    customDesign(
      texxt: "Mix Meal",
      image: "images/Mix2Meal.png",
      cat: 'Offer',
      rate: '⭐⭐⭐⭐',
      Oprice: '90.00',
      Dprice: '55.00',
    ),
    customDesign(
      texxt: "Grand Share",
      image: "images/Grand-Share2.png",
      cat: 'Offer',
      rate: '⭐⭐⭐⭐',
      Oprice: '289.00',
      Dprice: '235.00',
    ),
    customDesign(
      texxt: "Big Mac",
      image: "images/Bigmac.png",
      Oprice: '95.00',
      Dprice: '52.00',
      rate: '⭐⭐',
      cat: 'Beef & Chicken',
    ),
    customDesign(
      texxt: "Big Tasty",
      image: "images/Big-tasty-Beef.png",
      cat: 'Beef & Chicken',
      rate: '⭐⭐⭐⭐',
      Oprice: '120.00',
      Dprice: '88.00',
    ),
    customDesign(
      texxt: "McRoyal",
      image: "images/McRoyal.png",
      cat: 'Beef',
      rate: '⭐⭐⭐',
      Oprice: '114.00',
      Dprice: '74.00',
    ),
    customDesign(
      texxt: "Chicken Fillet",
      image: "images/Chicken-Fillet.png",
      cat: 'Chicken',
      rate: '⭐⭐⭐',
      Oprice: '86.00',
      Dprice: '65.00',
    ),
    customDesign(
      texxt: "Grand Chicken",
      image: "images/Grand Chicken Regular.png",
      cat: 'Chicken',
      rate: '⭐⭐',
      Oprice: '120.00',
      Dprice: '88.00',
    ),
    customDesign(
      texxt: "Cheese Fries",
      image: "images/Cheese-Fries.png",
      cat: 'Sides',
      rate: '⭐⭐⭐⭐',
      Oprice: '120.00',
      Dprice: '88.00',
    ),
    customDesign(
      texxt: "Cappuccino",
      image: "images/Cappuccino.png",
      cat: 'Hot Drinks',
      rate: '⭐⭐',
      Oprice: '46.00',
      Dprice: '30.00',
    ),
    customDesign(
      texxt: "Coca Cola Zero",
      image: "images/ZeroCola.png",
      cat: 'Cold Drinks',
      rate: '⭐⭐⭐⭐',
      Oprice: '36.00',
      Dprice: '24.00',
    ),
    customDesign(
      texxt: "Milkshake Vanilla",
      image: "images/Milkshake-Vanilla.png",
      cat: 'Sweet Drinks',
      rate: '⭐⭐⭐',
      Oprice: '49.00',
      Dprice: '36.50',
    ),
    customDesign(
      texxt: "Caramel",
      image: "images/Caramel.png",
      cat: 'Sandae',
      rate: '⭐⭐⭐⭐',
      Oprice: '46.00',
      Dprice: '36.00',
    ),
  ];
  static List favLista = [
    favComponent(
      texxt: "Mix Meal",
      image: "images/Mix2Meal.png",
      cat: 'Offer',
      rate: '⭐⭐⭐⭐',
      Oprice: '90.00',
      Dprice: '55.00',
    ),
    favComponent(
      texxt: "Grand Share",
      image: "images/Grand-Share2.png",
      cat: 'Offer',
      rate: '⭐⭐⭐⭐',
      Oprice: '289.00',
      Dprice: '235.00',
    ),
    favComponent(
      texxt: "Big Mac",
      image: "images/Bigmac.png",
      Oprice: '95.00',
      Dprice: '52.00',
      rate: '⭐⭐',
      cat: 'Beef & Chicken',
    ),
    favComponent(
      texxt: "Big Tasty",
      image: "images/Big-tasty-Beef.png",
      cat: 'Beef & Chicken',
      rate: '⭐⭐⭐⭐',
      Oprice: '120.00',
      Dprice: '88.00',
    ),
    favComponent(
      texxt: "McRoyal",
      image: "images/McRoyal.png",
      cat: 'Beef',
      rate: '⭐⭐⭐',
      Oprice: '114.00',
      Dprice: '74.00',
    ),
    favComponent(
      texxt: "Chicken Fillet",
      image: "images/Chicken-Fillet.png",
      cat: 'Chicken',
      rate: '⭐⭐⭐',
      Oprice: '86.00',
      Dprice: '65.00',
    ),
    favComponent(
      texxt: "Grand Chicken",
      image: "images/Grand Chicken Regular.png",
      cat: 'Chicken',
      rate: '⭐⭐',
      Oprice: '120.00',
      Dprice: '88.00',
    ),
    favComponent(
      texxt: "Cheese Fries",
      image: "images/Cheese-Fries.png",
      cat: 'Sides',
      rate: '⭐⭐⭐⭐',
      Oprice: '120.00',
      Dprice: '88.00',
    ),
    favComponent(
      texxt: "Cappuccino",
      image: "images/Cappuccino.png",
      cat: 'Hot Drinks',
      rate: '⭐⭐',
      Oprice: '46.00',
      Dprice: '30.00',
    ),
    favComponent(
      texxt: "Coca Cola Zero",
      image: "images/ZeroCola.png",
      cat: 'Cold Drinks',
      rate: '⭐⭐⭐⭐',
      Oprice: '36.00',
      Dprice: '24.00',
    ),
    favComponent(
      texxt: "Milkshake Vanilla",
      image: "images/Milkshake-Vanilla.png",
      cat: 'Sweet Drinks',
      rate: '⭐⭐⭐',
      Oprice: '49.00',
      Dprice: '36.50',
    ),
    favComponent(
      texxt: "Caramel",
      image: "images/Caramel.png",
      cat: 'Sandae',
      rate: '⭐⭐⭐⭐',
      Oprice: '46.00',
      Dprice: '36.00',
    ),
  ];
  static List favReversed = new List.from(favLista.reversed);
}
